FROM python:3-alpine3.20 AS base

WORKDIR /app

FROM base AS reqs 
RUN pip install flask==3.1.0
RUN pip install waitress==3.0.2

FROM reqs AS app
RUN mkdir /app/templates
COPY *.jinja2 /app/templates
COPY app.py app.py

ENV AOC_TOKEN=
EXPOSE 8080

VOLUME images

ENTRYPOINT waitress-serve app:app
